version: '2'

services:
  database:
    image: cockroachdb/cockroach
    ports:
      - 26257:26257
    networks:
      - db
    command: ["start", "--insecure"]
  smtpd:
    image: honeybadger
    build: .
    depends_on:
      - database
    ports:
      - 2525:2525
    networks:
      - db
      - public
    environment:
      - COCKROACHDB_URL=postgres://root@database:26257/honeybadger?sslmode=disable
  webserver:
    image: honeybadger
    build: .
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - db
      - public
    environment:
      - COCKROACHDB_URL=postgres://root@database:26257/honeybadger?sslmode=disable
    command: ["/usr/local/bin/webserver"]
  migrate:
    image: migrate
    build:
      dockerfile: ./scripts/Dockerfile.migrate
      context: ./
    volumes:
      - "./migrations:/migrations"
    depends_on:
      - database
    networks:
      - db
    entrypoint: /bin/sh setup_database.sh
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - public
      - db
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    ports:
      - 8086:8086
    networks:
      - db
    volumes:
      - influxdb-volume:/var/lib/influxdb

networks:
  db:
    internal: true
  public:
    external: true

volumes:
  grafana-volume:
  influxdb-volume:

